#include <bits/stdc++.h>
using namespace std;
int main()
{
    long long t,i,j,n;
    cin>>t;
    while(t--)
    {
        long long ans=0,maxi=-1000000001,mini=-1000000001;
        cin>>n;
        vector<long long> v1(n),pos,neg;
        for(i=0;i<n;i++)
        {
            cin>>v1[i];
            if(v1[i]<0)
                neg.push_back(i);
            else 
                pos.push_back(i);
        }
        i=0;j=0;
        while(i<pos.size() && j<neg.size())
        {
            if(pos[i]<neg[j])
            {
                if(i+1!=pos.size())
                {
                    if(pos[i]+1==pos[i+1])
                        maxi=max(maxi,v1[pos[i++]]);
                    else
                    { 
                        if(maxi==-1000000001)
                            ans+=v1[pos[i]];
                        else 
                        {
                            maxi=max(maxi,v1[pos[i]]);
                            ans+=maxi;
                        }
                        maxi=-1000000001;
                        i++;
                    }
                }
                else 
                {
                    if(maxi==-1000000001)
                        ans+=v1[pos[i]];
                    else 
                    {
                        maxi=max(maxi,v1[pos[i]]);
                        ans+=maxi;
                    }
                    maxi=-1000000001;
                    i++;
                }
            }
            else 
            {
                if(j+1!=neg.size())
                {
                    if(neg[j]+1==neg[j+1])
                        mini=max(mini,v1[neg[j++]]);
                    else
                    { 
                        if(mini==-1000000001)
                            ans+=v1[neg[j]];
                        else 
                        {
                            mini=max(mini,v1[neg[j]]);
                            ans+=mini;
                        }
                        mini=-1000000001;
                        j++;
                    }
                }
                else 
                {
                    if(mini==-1000000001)
                        ans+=v1[neg[j]];
                    else 
                    {
                        mini=max(mini,v1[neg[j]]);
                        ans+=mini;
                    }
                    mini=-1000000001;
                    j++;
                }
            }
        }
        if(i==pos.size())
        {
            mini=-1000000001;
            while(j<neg.size())
                mini=max(mini,v1[neg[j++]]);
            ans+=mini;
        }
        else if(j==neg.size())
        {
            maxi=-1000000001;
            while(i<pos.size())
                maxi=max(maxi,v1[pos[i++]]);
            ans+=maxi;
        }
        cout<<ans<<endl;
    }
}