#include<bits/stdc++.h>
using namespace std;
int main()
{
    int n,i,c1=0,c2=0,c3=0,c4=0,k;
    cin>>n;
    int a[n];
    for(i=0;i<n;i++) {
        cin>>a[i];
        if(a[i]==1)
            c1++;
        if(a[i]==2)
            c2++;
        if(a[i]==3)
            c3++;
        if(a[i]==4)
            c4++; }
    k=c4;
    if(c1<=c3)
    {
        k=k+c3+(c2/2);
        if(c2%2==1)
            k++;
    }
    else
    {
        k=k+c3;
        c1=c1-c3;
        if(c1%2==0)
        {
            if((c1/2)==c2)
                k=k+c2;
            if((c1/2)<c2)
            {
                k=k+(c1/2);
                c2=c2-(c1/2);
                k=k+(c2/2);
                if(c2%2==1)
                    k++;
            }
            if((c1/2)>c2)
            {
                k=k+c2;
                c1=2*((c1/2)-c2);
                if(c1>=4)
                k=k+(c1/4)+(c1%4);
                else
                k++;
            }
        }
        else 
        {
            if(c1/2==c2)
                k=k+c2+1;
            if((c1/2)<c2)
            {
                k=k+(c1/2)+1;
                c2=c2-(c1/2)-1;
                k=k+(c2/2);
                if(c2%2==1)
                    k++;
            }
            if((c1/2)>c2)
            {
                k=k+c2;
                c1=2*((c1/2)-c2)+1;
                if(c1>=4)
                k=k+(c1/4)+(c1%4);
                else
                k++;
            }
        }
    }
    cout<<k<<endl;
}