#include<bits/stdc++.h>
using namespace std;
int main()
{
    int t,k,i;
    cin>>t;
    for(k=0;k<t;k++)
    {
        string s1,s2;
        cin>>s1;
        int sum=0,p,a[10]={0};
        for(i=0;i<s1.length();i++)
        {
            s2=s1[i];
            p=stoi(s2);
            sum=sum+p;
            a[p]++;   
        }
        p=sum%9;
        if(p==0)
        {
            cout<<"YES"<<endl;
            continue;
        }
        if(p==1)
        {
            if(a[2]>=4||(a[2]>=1&&a[3]>=1))
                cout<<"YES"<<endl;
            else 
                cout<<"NO"<<endl;
            continue;
        }
        if(p==2)
        {
            if((a[2]>=8)||(a[2]>=2&&a[3]>=2)||(a[2]>=5&&a[3]>=1))
                cout<<"YES"<<endl;
            else 
                cout<<"NO"<<endl;
            continue;
        }
        if(p==3)
        {
            if(a[2]>=3||a[3]>=1)
                cout<<"YES"<<endl;
            else 
                cout<<"NO"<<endl;
            continue;
        }
        if(p==4)
        {
            if((a[2]>=7)||(a[2]>=1&&a[3]>=2)||(a[2]>=4&&a[3]>=1))
                cout<<"YES"<<endl;
            else 
                cout<<"NO"<<endl;
            continue;
        }
        if(p==5)
        {
            if(a[2]>=2)
                cout<<"YES"<<endl;
            else 
                cout<<"NO"<<endl;
            continue;
        }
        if(p==6)
        {
            if(a[2]>=6||a[3]>=2||(a[2]>=3&&a[3]>=1))
                cout<<"YES"<<endl;
            else 
                cout<<"NO"<<endl;
            continue;
        }
        if(p==7)
        {
            if(a[2]>=1)
                cout<<"YES"<<endl;
            else 
                cout<<"NO"<<endl;
            continue;
        }
        if(p==8)
        {
            if(a[2]>=5||(a[2]>=2&&a[3]>=1))
                cout<<"YES"<<endl;
            else 
                cout<<"NO"<<endl;
        }
    }
}