#include<bits/stdc++.h>
using namespace std;
int main()
{
    string arr[3] ;
    int i,j,cntx=0,cnt0=0,cntd=0,p=0,q=0;
    for(i=0;i<3;i++)
    {
            cin>>arr[i];
            if(arr[i][0]=='X')
                cntx++;
            if(arr[i][0]=='0')
                cnt0++;
            if(arr[i][0]=='.')
                cntd++;
            if(arr[i][1]=='X')
                cntx++;
            if(arr[i][1]=='0')
                cnt0++;
            if(arr[i][1]=='.')
                cntd++;
            if(arr[i][2]=='X')
                cntx++;
            if(arr[i][2]=='0')
                cnt0++;
            if(arr[i][2]=='.')
                cntd++;
    }
    if(cntx-cnt0==1||cntx-cnt0==0)
    {
        if(arr[0][0]=='X'&&arr[0][1]=='X'&&arr[0][2]=='X')
            p=1;
        if(arr[1][0]=='X'&&arr[1][1]=='X'&&arr[1][2]=='X')
            p=1;
        if(arr[2][0]=='X'&&arr[2][1]=='X'&&arr[2][2]=='X')
            p=1;
        if(arr[0][0]=='X'&&arr[1][0]=='X'&&arr[2][0]=='X')
            p=1;
        if(arr[0][1]=='X'&&arr[1][1]=='X'&&arr[2][1]=='X')
            p=1;
        if(arr[0][2]=='X'&&arr[1][2]=='X'&&arr[2][2]=='X')
            p=1;
        if(arr[0][0]=='X'&&arr[1][1]=='X'&&arr[2][2]=='X')
            p=1;
        if(arr[0][2]=='X'&&arr[1][1]=='X'&&arr[2][0]=='X')
            p=1;
        if(arr[0][0]=='0'&&arr[0][1]=='0'&&arr[0][2]=='0')
            q=1;
        if(arr[1][0]=='0'&&arr[1][1]=='0'&&arr[1][2]=='0')
            q=1;
        if(arr[2][0]=='0'&&arr[2][1]=='0'&&arr[2][2]=='0')
            q=1;
        if(arr[0][0]=='0'&&arr[1][0]=='0'&&arr[2][0]=='0')
            q=1;
        if(arr[0][1]=='0'&&arr[1][1]=='0'&&arr[2][1]=='0')
            q=1;
        if(arr[0][2]=='0'&&arr[1][2]=='0'&&arr[2][2]=='0')
            q=1;
        if(arr[0][0]=='0'&&arr[1][1]=='0'&&arr[2][2]=='0')
            q=1;
        if(arr[0][2]=='0'&&arr[1][1]=='0'&&arr[2][0]=='0')
            q=1;
        if(p==1&&q==1)
        {
            cout<<"illegal";
            exit(0);
        }
        if(p==1)
        {
            if(cntx-cnt0==1)
            {
                cout<<"the first player won";
                exit(0);
            }
            else 
            {
                cout<<"illegal";
                exit(0);
            }
        }
        if(q==1)
        {
            if(cntx-cnt0==0)
            {
                cout<<"the second player won";
                exit(0);
            }
            else 
            {
                cout<<"illegal";
                exit(0);
            }
        }
        if(cntd==0)
            cout<<"draw";
        else 
        {
            if(cntx-cnt0==1)
                cout<<"second";
            else 
                cout<<"first";
        }
    }
    else 
        cout<<"illegal";
}