#include<bits/stdc++.h>
using namespace std;
int main()
{
    string s1,s2;
    cin>>s1;
    int a[10]={0},num,i,j,k;
    for(i=0;i<s1.length();i++)
        a[s1[i]-'0']++;
    if(a[0]!=0)
    {
        cout<<"YES"<<endl<<0<<endl;
        exit(0);
    }
    if(a[8]!=0)
    {
        cout<<"YES"<<endl<<8<<endl;
        exit(0);
    }
    if(s1.size()==1)
    {
        cout<<"NO"<<endl;
        exit(0);
    }
    else if(s1.size()==2)
    {
        num=stoi(s1);
        if(num%8==0)
            cout<<"YES"<<endl<<num<<endl;
        else 
            cout<<"NO"<<endl;
        exit(0);
    }
    else if(s1.size()==3)
    {
        num=stoi(s1);
        if(num%8==0)
        {
            cout<<"YES"<<endl<<num<<endl;
            exit(0);
        }
        else 
        {
            for(i=0;i<s1.length();i++)
            {
                for(j=i+1;j<s1.length();j++)
                {
                    s2.push_back(s1[i]);
                    s2.push_back(s1[j]);
                    num=stoi(s2);
                    if(num%8==0)
                    {
                        cout<<"YES"<<endl<<s2<<endl;
                        exit(0);
                    }
                    s2.erase();
                }
            }
        }
    }
    else 
    {
        for(i=0;i<s1.length();i++)
        {
            for(j=i+1;j<s1.length();j++)
            {
                s2.push_back(s1[i]);
                s2.push_back(s1[j]);
                num=stoi(s2);
                if(num%8==0)
                {
                    cout<<"YES"<<endl<<s2<<endl;
                    exit(0);
                }
                s2.erase();
            }
        }
        for(i=0;i<s1.length();i++)
        {
            for(j=i+1;j<s1.length();j++)
            {
                for(k=j+1;k<s1.length();k++)
                {
                    s2.push_back(s1[i]);
                    s2.push_back(s1[j]);
                    s2.push_back(s1[k]);
                    num=stoi(s2);
                    if(num%8==0)
                    {
                        cout<<"YES"<<endl<<s2<<endl;
                        exit(0);
                    }
                    s2.erase();
                }
            }
        }
    }
    cout<<"NO"<<endl;
}